# Generated by Django 4.1.3 on 2023-04-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasure',
            name='supreme_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='to_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_unit', to='main_app.unitofmeasure'),
        ),
    ]
