# Generated by Django 4.1.3 on 2023-05-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_unitofmeasure_supreme_unit_alter_conversion_to_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='cookingstage',
            name='image',
            field=models.ImageField(blank=True, max_length=130, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, max_length=130, null=True, upload_to=''),
        ),
    ]
