# Generated by Django 4.1.3 on 2023-10-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_user_managers_remove_user_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
