# Generated by Django 4.1.3 on 2023-10-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='address_city_street',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_address_city_street',
        ),
        migrations.AddField(
            model_name='product',
            name='address_city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='address_street',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_address_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_address_street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='address_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_address_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
