.TH "admin.py" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
admin.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbym\fP"
.br
.ti -1c
.RI "namespace \fBbym\&.BYM_project\fP"
.br
.ti -1c
.RI "namespace \fBbym\&.BYM_project\&.main_app\fP"
.br
.ti -1c
.RI "namespace \fBbym\&.BYM_project\&.main_app\&.admin\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
