.TH "bym.BYM_project.main_app.models.Menu.Meta" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.Menu.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBverbose_name\fP = 'Меню'"
.br
.ti -1c
.RI "str \fBverbose_name_plural\fP = 'Меню'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB232\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str bym\&.BYM_project\&.main_app\&.models\&.Menu\&.Meta\&.verbose_name = 'Меню'\fC [static]\fP"

.PP
Definition at line \fB233\fP of file \fBmodels\&.py\fP\&.
.SS "str bym\&.BYM_project\&.main_app\&.models\&.Menu\&.Meta\&.verbose_name_plural = 'Меню'\fC [static]\fP"

.PP
Definition at line \fB234\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
