.TH "bym.BYM_project.main_app.models.Product.Meta" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.Product.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBverbose_name\fP = 'Продукт из магазина'"
.br
.ti -1c
.RI "str \fBverbose_name_plural\fP = 'Продукты из магазинов'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB267\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str bym\&.BYM_project\&.main_app\&.models\&.Product\&.Meta\&.verbose_name = 'Продукт из магазина'\fC [static]\fP"

.PP
Definition at line \fB268\fP of file \fBmodels\&.py\fP\&.
.SS "str bym\&.BYM_project\&.main_app\&.models\&.Product\&.Meta\&.verbose_name_plural = 'Продукты из магазинов'\fC [static]\fP"

.PP
Definition at line \fB269\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
