.TH "bym.BYM_project.main_app.models.DishCategory.Meta" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.DishCategory.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBverbose_name\fP = 'Продукт в блюде'"
.br
.ti -1c
.RI "str \fBverbose_name_plural\fP = 'Продукты в блюдах'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB197\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str bym\&.BYM_project\&.main_app\&.models\&.DishCategory\&.Meta\&.verbose_name = 'Продукт в блюде'\fC [static]\fP"

.PP
Definition at line \fB198\fP of file \fBmodels\&.py\fP\&.
.SS "str bym\&.BYM_project\&.main_app\&.models\&.DishCategory\&.Meta\&.verbose_name_plural = 'Продукты в блюдах'\fC [static]\fP"

.PP
Definition at line \fB199\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
