.TH "bym.BYM_project.main_app.models.SubType.Meta" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.SubType.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBverbose_name\fP = 'Подтип блюда'"
.br
.ti -1c
.RI "str \fBverbose_name_plural\fP = 'Подтипы блюд'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB81\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str bym\&.BYM_project\&.main_app\&.models\&.SubType\&.Meta\&.verbose_name = 'Подтип блюда'\fC [static]\fP"

.PP
Definition at line \fB82\fP of file \fBmodels\&.py\fP\&.
.SS "str bym\&.BYM_project\&.main_app\&.models\&.SubType\&.Meta\&.verbose_name_plural = 'Подтипы блюд'\fC [static]\fP"

.PP
Definition at line \fB83\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
