.TH "bym.BYM_project.main_app.models.Order" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.Order \- информация о заказах\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMeta\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBuser\fP"
.br
.ti -1c
.RI "\fBUser\fP"
.br
.ti -1c
.RI "\fBon_delete\fP"
.br
.ti -1c
.RI "\fBorder_date\fP = models\&.DateTimeField()"
.br
.ti -1c
.RI "\fBcurrent\fP = models\&.BooleanField(default=True)"
.br
.in -1c
.SH "Detailed Description"
.PP 
информация о заказах\&. 


.br
 order_date – дата заказа 
.br
 current – статус (выполнен/ не выполнен) 
.br
 user_id – пользователь совершивший заказ 
.br
 
.PP
Definition at line \fB208\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bym\&.BYM_project\&.main_app\&.models\&.Order\&.current = models\&.BooleanField(default=True)\fC [static]\fP"

.PP
Definition at line \fB222\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.Order\&.on_delete\fC [static]\fP"

.PP
Definition at line \fB219\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.Order\&.order_date = models\&.DateTimeField()\fC [static]\fP"

.PP
Definition at line \fB221\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.Order\&.user\fC [static]\fP"

.PP
Definition at line \fB219\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.Order\&.User\fC [static]\fP"

.PP
Definition at line \fB219\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
