.TH "bym.BYM_project.main_app.models.SubType" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.SubType \- таблица с подтипами блюд 
.br
 name – название подтипа (например фруктовые десерты) 
.br
 type_id – тип к которому относится подтип 
.br
  

.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMeta\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBtype\fP"
.br
.ti -1c
.RI "\fBType\fP"
.br
.ti -1c
.RI "\fBon_delete\fP"
.br
.ti -1c
.RI "\fBname\fP = models\&.CharField(max_length=30)"
.br
.in -1c
.SH "Detailed Description"
.PP 
таблица с подтипами блюд 
.br
 name – название подтипа (например фруктовые десерты) 
.br
 type_id – тип к которому относится подтип 
.br
 
.PP
Definition at line \fB75\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bym\&.BYM_project\&.main_app\&.models\&.SubType\&.name = models\&.CharField(max_length=30)\fC [static]\fP"

.PP
Definition at line \fB87\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.SubType\&.on_delete\fC [static]\fP"

.PP
Definition at line \fB85\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.SubType\&.type\fC [static]\fP"

.PP
Definition at line \fB85\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.SubType\&.Type\fC [static]\fP"

.PP
Definition at line \fB85\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
