.TH "bym.BYM_project.main_app" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBadmin\fP"
.br
.ti -1c
.RI "namespace \fBapps\fP"
.br
.ti -1c
.RI "namespace \fBcart\fP"
.br
.ti -1c
.RI "namespace \fBconfig\fP"
.br
.ti -1c
.RI "namespace \fBconversions_functions\fP"
.br
.ti -1c
.RI "namespace \fBforms\fP"
.br
.ti -1c
.RI "namespace \fBfunctions_backend\fP"
.br
.ti -1c
.RI "namespace \fBmodels\fP"
.br
.ti -1c
.RI "namespace \fBparser\fP"
.br
.ti -1c
.RI "namespace \fBrecommendation_system\fP"
.br
.ti -1c
.RI "namespace \fBsearch\fP"
.br
.ti -1c
.RI "namespace \fBserializers\fP"
.br
.ti -1c
.RI "namespace \fBtests\fP"
.br
.ti -1c
.RI "namespace \fBviews\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
