.TH "bym.BYM_project.main_app.parser.Parser" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.parser.Parser \- Определяет базавый класс используемый для парсинга всех сайтов  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBbym\&.BYM_project\&.main_app\&.parser\&.Lavka\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, user_id, shop_id)"
.br
.RI "Инициализирует класс Parser\&. "
.ti -1c
.RI "\fBsql_script\fP (self)"
.br
.RI "Сохраняет в базу данных "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuser_obj\fP"
.br
.ti -1c
.RI "\fBoptions\fP"
.br
.ti -1c
.RI "\fBproduct_list\fP"
.br
.ti -1c
.RI "\fBshop_obj\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Определяет базавый класс используемый для парсинга всех сайтов 
.PP
Definition at line \fB23\fP of file \fBparser\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "bym\&.BYM_project\&.main_app\&.parser\&.Parser\&.__init__ ( self,  user_id,  shop_id)"

.PP
Инициализирует класс Parser\&. 
.PP
\fBParameters\fP
.RS 4
\fIuser_id\fP 
.br
\fIshop_id\fP 
.RE
.PP

.PP
Reimplemented in \fBbym\&.BYM_project\&.main_app\&.parser\&.Lavka\fP\&.
.PP
Definition at line \fB28\fP of file \fBparser\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bym\&.BYM_project\&.main_app\&.parser\&.Parser\&.sql_script ( self)"

.PP
Сохраняет в базу данных 
.PP
Definition at line \fB39\fP of file \fBparser\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bym\&.BYM_project\&.main_app\&.parser\&.Parser\&.options"

.PP
Definition at line \fB35\fP of file \fBparser\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.parser\&.Parser\&.product_list"

.PP
Definition at line \fB36\fP of file \fBparser\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.parser\&.Parser\&.shop_obj"

.PP
Definition at line \fB37\fP of file \fBparser\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.parser\&.Parser\&.user_obj"

.PP
Definition at line \fB34\fP of file \fBparser\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
