.TH "bym.BYM_project.main_app.search" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.search
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSearchDish\fP"
.br
.RI "Класс реализует функционал поиска и сортировки блюд по строке поиска, фильтрам блюда, рекомендациям конткретному пользователю и указанному адресу "
.ti -1c
.RI "class \fBSearchProduct\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
