.TH "bym.BYM_project.main_app.views" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.views
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChangeCartApi\fP"
.br
.ti -1c
.RI "class \fBHomePageApi\fP"
.br
.ti -1c
.RI "class \fBParseProductsApi\fP"
.br
.ti -1c
.RI "class \fBSearchDishApi\fP"
.br
.ti -1c
.RI "class \fBUserApiView\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHomePageView\fP (request)"
.br
.ti -1c
.RI "\fBDish\fP (request, id)"
.br
.ti -1c
.RI "\fBFinalPage\fP (request)"
.br
.ti -1c
.RI "\fBmy_view\fP (request)"
.br
.ti -1c
.RI "\fBupdate_counter\fP (request)"
.br
.ti -1c
.RI "\fBparse_adress\fP (request)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bym\&.BYM_project\&.main_app\&.views\&.Dish ( request,  id)"

.PP
Definition at line \fB44\fP of file \fBviews\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.views\&.FinalPage ( request)"

.PP
Definition at line \fB71\fP of file \fBviews\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.views\&.HomePageView ( request)"

.PP
Definition at line \fB18\fP of file \fBviews\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.views\&.my_view ( request)"

.PP
Definition at line \fB89\fP of file \fBviews\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.views\&.parse_adress ( request)"

.PP
Definition at line \fB104\fP of file \fBviews\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.views\&.update_counter ( request)"

.PP
Definition at line \fB95\fP of file \fBviews\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
