.TH "bym.BYM_project.main_app.models.UnitOfMeasure" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.UnitOfMeasure \- единицы изменения 
.br
 name – название единицы измерения (например штуки или кг) 
.br
 supreme_unit_id – основная форма категории (например Supreme_unit_id у 'штуки' это 'штука') 
.br
  

.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMeta\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBsupreme_unit\fP"
.br
.ti -1c
.RI "\fBnull\fP"
.br
.ti -1c
.RI "\fBTrue\fP"
.br
.ti -1c
.RI "\fBblank\fP"
.br
.ti -1c
.RI "\fBon_delete\fP"
.br
.ti -1c
.RI "\fBname\fP = models\&.CharField(max_length=20)"
.br
.in -1c
.SH "Detailed Description"
.PP 
единицы изменения 
.br
 name – название единицы измерения (например штуки или кг) 
.br
 supreme_unit_id – основная форма категории (например Supreme_unit_id у 'штуки' это 'штука') 
.br
 
.PP
Definition at line \fB155\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bym\&.BYM_project\&.main_app\&.models\&.UnitOfMeasure\&.blank\fC [static]\fP"

.PP
Definition at line \fB165\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.UnitOfMeasure\&.name = models\&.CharField(max_length=20)\fC [static]\fP"

.PP
Definition at line \fB167\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.UnitOfMeasure\&.null\fC [static]\fP"

.PP
Definition at line \fB165\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.UnitOfMeasure\&.on_delete\fC [static]\fP"

.PP
Definition at line \fB165\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.UnitOfMeasure\&.supreme_unit\fC [static]\fP"

.PP
Definition at line \fB165\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.UnitOfMeasure\&.True\fC [static]\fP"

.PP
Definition at line \fB165\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
