.TH "bym.BYM_project.main_app.models.Type.Meta" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.Type.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBverbose_name\fP = 'Тип бдюда'"
.br
.ti -1c
.RI "str \fBverbose_name_plural\fP = 'Типы блюд'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB68\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str bym\&.BYM_project\&.main_app\&.models\&.Type\&.Meta\&.verbose_name = 'Тип бдюда'\fC [static]\fP"

.PP
Definition at line \fB69\fP of file \fBmodels\&.py\fP\&.
.SS "str bym\&.BYM_project\&.main_app\&.models\&.Type\&.Meta\&.verbose_name_plural = 'Типы блюд'\fC [static]\fP"

.PP
Definition at line \fB70\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
