.TH "bym.BYM_project.main_app.apps.MainAppConfig" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.apps.MainAppConfig
.SH SYNOPSIS
.br
.PP
.PP
Inherits AppConfig\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBdefault_auto_field\fP = 'django\&.db\&.models\&.BigAutoField'"
.br
.ti -1c
.RI "str \fBname\fP = 'main_app'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBapps\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str bym\&.BYM_project\&.main_app\&.apps\&.MainAppConfig\&.default_auto_field = 'django\&.db\&.models\&.BigAutoField'\fC [static]\fP"

.PP
Definition at line \fB5\fP of file \fBapps\&.py\fP\&.
.SS "str bym\&.BYM_project\&.main_app\&.apps\&.MainAppConfig\&.name = 'main_app'\fC [static]\fP"

.PP
Definition at line \fB6\fP of file \fBapps\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
