.TH "bym.BYM_project.main_app.parser" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.parser
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLavka\fP"
.br
.RI "Определяет класс используемый для парсинга лавки\&. "
.ti -1c
.RI "class \fBParser\fP"
.br
.RI "Определяет базавый класс используемый для парсинга всех сайтов "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBparse_by_address\fP (user_id, city_street, number)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bym\&.BYM_project\&.main_app\&.parser\&.parse_by_address ( user_id,  city_street,  number)"

.PP
Definition at line \fB16\fP of file \fBparser\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
