.TH "bym.BYM_project.main_app.models.Category.Meta" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.Category.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBverbose_name\fP = 'Категория продукта'"
.br
.ti -1c
.RI "str \fBverbose_name_plural\fP = 'Категории продуктов'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB146\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str bym\&.BYM_project\&.main_app\&.models\&.Category\&.Meta\&.verbose_name = 'Категория продукта'\fC [static]\fP"

.PP
Definition at line \fB147\fP of file \fBmodels\&.py\fP\&.
.SS "str bym\&.BYM_project\&.main_app\&.models\&.Category\&.Meta\&.verbose_name_plural = 'Категории продуктов'\fC [static]\fP"

.PP
Definition at line \fB148\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
