.TH "bym.BYM_project.main_app.config" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.config
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBwebdriver_name\fP = os\&.getenv('webdriver_name')"
.br
.ti -1c
.RI "list \fBurls_lavka\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list bym\&.BYM_project\&.main_app\&.config\&.urls_lavka"
\fBInitial value:\fP.PP
.nf
1 =  [
2     'https://lavka\&.yandex\&.ru/10743/category/ovoshchi_griby_i_zelen',
3     'https://lavka\&.yandex\&.ru/10743/category/Frukty_i_yagody',
4     'https://lavka\&.yandex\&.ru/10743/category/milk_products',
5     'https://lavka\&.yandex\&.ru/10743/category/cheese',
6     'https://lavka\&.yandex\&.ru/10743/category/kefir_smetana_tvorog',
7     'https://lavka\&.yandex\&.ru/10743/category/e64b861bd9a34ebc9103dbf15e2d2932',
8     'https://lavka\&.yandex\&.ru/10743/category/molochnoe_dlya_detej',
9     'https://lavka\&.yandex\&.ru/10743/category/hleb',
10     'https://lavka\&.yandex\&.ru/10743/category/vipechka',
11     'https://lavka\&.yandex\&.ru/10743/category/hlebcy',
12     'https://lavka\&.yandex\&.ru/10743/category/beef_pork',
13     'https://lavka\&.yandex\&.ru/10743/category/wurst_all',
14     'https://lavka\&.yandex\&.ru/10743/category/ryba_i_moreprodukty',
15     'https://lavka\&.yandex\&.ru/10743/category/zakuski_i_pashtety',
16     'https://lavka\&.yandex\&.ru/10743/category/morozhenoe',
17     'https://lavka\&.yandex\&.ru/10743/category/pelmeni_i_vareniki',
18     'https://lavka\&.yandex\&.ru/10743/category/frozen_vegetables_and_berries',
19     'https://lavka\&.yandex\&.ru/10743/category/deserty',
20     'https://lavka\&.yandex\&.ru/10743/category/polufabrikaty',
21     'https://lavka\&.yandex\&.ru/10743/category/553b84d49692448bb06588f9d694cbde',
22     'https://lavka\&.yandex\&.ru/10743/category/b9c6c90166f1487888de39b933119747',
23     'https://lavka\&.yandex\&.ru/10743/category/makarony_krupy_muka',
24     'https://lavka\&.yandex\&.ru/10743/category/hlopya_i_myusli',
25     'https://lavka\&.yandex\&.ru/10743/category/oils_sauces_spices',
26     'https://lavka\&.yandex\&.ru/10743/category/coffee_and_cocoa',
27     'https://lavka\&.yandex\&.ru/10743/category/tea',
28     'https://lavka\&.yandex\&.ru/10743/category/91ba4698f47f450087e3e8de50d93a15'
29 ]
.fi

.PP
Definition at line \fB8\fP of file \fBconfig\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.config\&.webdriver_name = os\&.getenv('webdriver_name')"

.PP
Definition at line \fB6\fP of file \fBconfig\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
