.TH "bym.BYM_project.main_app.models.Shop.Meta" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.Shop.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBverbose_name\fP = 'Магазин'"
.br
.ti -1c
.RI "str \fBverbose_name_plural\fP = 'Магазины'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB248\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str bym\&.BYM_project\&.main_app\&.models\&.Shop\&.Meta\&.verbose_name = 'Магазин'\fC [static]\fP"

.PP
Definition at line \fB249\fP of file \fBmodels\&.py\fP\&.
.SS "str bym\&.BYM_project\&.main_app\&.models\&.Shop\&.Meta\&.verbose_name_plural = 'Магазины'\fC [static]\fP"

.PP
Definition at line \fB250\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
