.TH "bym.BYM_project.main_app.views.UserApiView" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.views.UserApiView
.SH SYNOPSIS
.br
.PP
.PP
Inherits generics\&.ListAPIView\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBqueryset\fP = User\&.objects\&.all()"
.br
.ti -1c
.RI "\fBserializer_class\fP = \fBUserSerializer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB119\fP of file \fBviews\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bym\&.BYM_project\&.main_app\&.views\&.UserApiView\&.queryset = User\&.objects\&.all()\fC [static]\fP"

.PP
Definition at line \fB120\fP of file \fBviews\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.views\&.UserApiView\&.serializer_class = \fBUserSerializer\fP\fC [static]\fP"

.PP
Definition at line \fB121\fP of file \fBviews\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
