.TH "bym.BYM_project.main_app.serializers.UserSerializer.Meta" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.serializers.UserSerializer.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBmodel\fP = \fBUser\fP"
.br
.ti -1c
.RI "str \fBfields\fP = '__all__'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBserializers\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str bym\&.BYM_project\&.main_app\&.serializers\&.UserSerializer\&.Meta\&.fields = '__all__'\fC [static]\fP"

.PP
Definition at line \fB8\fP of file \fBserializers\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.serializers\&.UserSerializer\&.Meta\&.model = \fBUser\fP\fC [static]\fP"

.PP
Definition at line \fB7\fP of file \fBserializers\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
