.TH "bym.BYM_project.main_app.forms.SearchDishForm" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.forms.SearchDishForm
.SH SYNOPSIS
.br
.PP
.PP
Inherits forms\&.Form\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBsearch_string\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBforms\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bym\&.BYM_project\&.main_app\&.forms\&.SearchDishForm\&.search_string\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  forms\&.CharField(widget=forms\&.TextInput(attrs={
        "id": "search\-input\-id",
        "class": "i1ypu1yl",
        "value": "",
        "aria\-label": "Поиск",
        "autocomplete": "off",
        "placeholder": "Найти блюдо"
    }))
.fi

.PP
Definition at line \fB5\fP of file \fBforms\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
