.TH "bym.BYM_project.main_app.models.Conversion.Meta" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.Conversion.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBverbose_name\fP = 'Преобразование единицы измерения'"
.br
.ti -1c
.RI "str \fBverbose_name_plural\fP = 'Преобразования единиц измерения'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB178\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str bym\&.BYM_project\&.main_app\&.models\&.Conversion\&.Meta\&.verbose_name = 'Преобразование единицы измерения'\fC [static]\fP"

.PP
Definition at line \fB179\fP of file \fBmodels\&.py\fP\&.
.SS "str bym\&.BYM_project\&.main_app\&.models\&.Conversion\&.Meta\&.verbose_name_plural = 'Преобразования единиц измерения'\fC [static]\fP"

.PP
Definition at line \fB180\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
