.TH "bym.BYM_project.main_app.models.Dish.Meta" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.Dish.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBverbose_name\fP = 'Блюдо'"
.br
.ti -1c
.RI "str \fBverbose_name_plural\fP = 'Блюда'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB104\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str bym\&.BYM_project\&.main_app\&.models\&.Dish\&.Meta\&.verbose_name = 'Блюдо'\fC [static]\fP"

.PP
Definition at line \fB105\fP of file \fBmodels\&.py\fP\&.
.SS "str bym\&.BYM_project\&.main_app\&.models\&.Dish\&.Meta\&.verbose_name_plural = 'Блюда'\fC [static]\fP"

.PP
Definition at line \fB106\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
