.TH "bym.BYM_project.main_app.recommendation_system.RecommendationSystem" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.recommendation_system.RecommendationSystem
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "\fBfit\fP (self, X, y)"
.br
.ti -1c
.RI "\fBpredict\fP (self, X, y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1\fP of file \fBrecommendation_system\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "bym\&.BYM_project\&.main_app\&.recommendation_system\&.RecommendationSystem\&.__init__ ( self)"

.PP
Definition at line \fB2\fP of file \fBrecommendation_system\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bym\&.BYM_project\&.main_app\&.recommendation_system\&.RecommendationSystem\&.fit ( self,  X,  y)"

.PP
Definition at line \fB5\fP of file \fBrecommendation_system\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.recommendation_system\&.RecommendationSystem\&.predict ( self,  X,  y)"

.PP
Definition at line \fB8\fP of file \fBrecommendation_system\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
