.TH "bym.BYM_project.main_app.models.Country.Meta" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.Country.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBverbose_name\fP = 'Страна'"
.br
.ti -1c
.RI "str \fBverbose_name_plural\fP = 'Страны'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB56\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str bym\&.BYM_project\&.main_app\&.models\&.Country\&.Meta\&.verbose_name = 'Страна'\fC [static]\fP"

.PP
Definition at line \fB57\fP of file \fBmodels\&.py\fP\&.
.SS "str bym\&.BYM_project\&.main_app\&.models\&.Country\&.Meta\&.verbose_name_plural = 'Страны'\fC [static]\fP"

.PP
Definition at line \fB58\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
