.TH "bym.BYM_project.main_app.cart" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.cart
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCart\fP"
.br
.RI "Класс для работы с карзиной пользователья "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
