.TH "bym.BYM_project.main_app.models.Shop" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.Shop \- информация о магазине 
.br
 name – название магазина 
.br
 link – ссылка на магазин 
.br
  

.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMeta\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBmax_length\fP"
.br
.ti -1c
.RI "\fBlink\fP = models\&.URLField()"
.br
.in -1c
.SH "Detailed Description"
.PP 
информация о магазине 
.br
 name – название магазина 
.br
 link – ссылка на магазин 
.br
 
.PP
Definition at line \fB242\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bym\&.BYM_project\&.main_app\&.models\&.Shop\&.link = models\&.URLField()\fC [static]\fP"

.PP
Definition at line \fB253\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.Shop\&.max_length\fC [static]\fP"

.PP
Definition at line \fB252\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.Shop\&.name\fC [static]\fP"

.PP
Definition at line \fB252\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
