.TH "bym.BYM_project.main_app.models.UnitOfMeasure.Meta" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.UnitOfMeasure.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBverbose_name\fP = 'Единица измерения'"
.br
.ti -1c
.RI "str \fBverbose_name_plural\fP = 'Единицы измерения'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB161\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str bym\&.BYM_project\&.main_app\&.models\&.UnitOfMeasure\&.Meta\&.verbose_name = 'Единица измерения'\fC [static]\fP"

.PP
Definition at line \fB162\fP of file \fBmodels\&.py\fP\&.
.SS "str bym\&.BYM_project\&.main_app\&.models\&.UnitOfMeasure\&.Meta\&.verbose_name_plural = 'Единицы измерения'\fC [static]\fP"

.PP
Definition at line \fB163\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
