.TH "bym.BYM_project.main_app.models.ProductLog.Meta" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.ProductLog.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBverbose_name\fP = 'Лог родукта из магазина'"
.br
.ti -1c
.RI "str \fBverbose_name_plural\fP = 'Логи родуктов из магазинов'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB293\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str bym\&.BYM_project\&.main_app\&.models\&.ProductLog\&.Meta\&.verbose_name = 'Лог родукта из магазина'\fC [static]\fP"

.PP
Definition at line \fB294\fP of file \fBmodels\&.py\fP\&.
.SS "str bym\&.BYM_project\&.main_app\&.models\&.ProductLog\&.Meta\&.verbose_name_plural = 'Логи родуктов из магазинов'\fC [static]\fP"

.PP
Definition at line \fB295\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
