.TH "bym.BYM_project.main_app.recommendation_system" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.recommendation_system
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRecommendationSystem\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
