.TH "bym.BYM_project.main_app.models.Type" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.Type \- таблица с типами блюд 
.br
 name – название типа (например Завтраки) 
.br
  

.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMeta\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBmax_length\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
таблица с типами блюд 
.br
 name – название типа (например Завтраки) 
.br
 
.PP
Definition at line \fB63\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bym\&.BYM_project\&.main_app\&.models\&.Type\&.max_length\fC [static]\fP"

.PP
Definition at line \fB72\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.Type\&.name\fC [static]\fP"

.PP
Definition at line \fB72\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
