.TH "bym.BYM_project.main_app.models.Category" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.Category \- категории различных продуктов для приготовления 
.br
 name – название категории (например: бакалея или помидоры) 
.br
 supreme_category_id – надкатегория (например надкатегорией римских помидор являются помидоры) 
.br
  

.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMeta\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBsupreme_category\fP"
.br
.ti -1c
.RI "\fBnull\fP"
.br
.ti -1c
.RI "\fBTrue\fP"
.br
.ti -1c
.RI "\fBblank\fP"
.br
.ti -1c
.RI "\fBon_delete\fP"
.br
.ti -1c
.RI "\fBname\fP = models\&.CharField(max_length=70)"
.br
.in -1c
.SH "Detailed Description"
.PP 
категории различных продуктов для приготовления 
.br
 name – название категории (например: бакалея или помидоры) 
.br
 supreme_category_id – надкатегория (например надкатегорией римских помидор являются помидоры) 
.br
 
.PP
Definition at line \fB140\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bym\&.BYM_project\&.main_app\&.models\&.Category\&.blank\fC [static]\fP"

.PP
Definition at line \fB150\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.Category\&.name = models\&.CharField(max_length=70)\fC [static]\fP"

.PP
Definition at line \fB152\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.Category\&.null\fC [static]\fP"

.PP
Definition at line \fB150\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.Category\&.on_delete\fC [static]\fP"

.PP
Definition at line \fB150\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.Category\&.supreme_category\fC [static]\fP"

.PP
Definition at line \fB150\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.Category\&.True\fC [static]\fP"

.PP
Definition at line \fB150\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
