.TH "bym.BYM_project.main_app.models.CookingStage" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bym.BYM_project.main_app.models.CookingStage \- шаги для приготовления блюда 
.br
 description – текст того, что нужно сделать на этом шаге 
.br
 order – порядковый номер шага 
.br
 dish_id – блюдо, к которому относится этот шаг 
.br
 image – ссылка на изображение шага 
.br
  

.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMeta\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBdish\fP"
.br
.ti -1c
.RI "\fBDish\fP"
.br
.ti -1c
.RI "\fBon_delete\fP"
.br
.ti -1c
.RI "\fBdescription\fP = models\&.TextField()"
.br
.ti -1c
.RI "\fBorder\fP = models\&.PositiveIntegerField()"
.br
.ti -1c
.RI "\fBimage\fP = models\&.ImageField(null=True, blank=True, max_length=130)"
.br
.in -1c
.SH "Detailed Description"
.PP 
шаги для приготовления блюда 
.br
 description – текст того, что нужно сделать на этом шаге 
.br
 order – порядковый номер шага 
.br
 dish_id – блюдо, к которому относится этот шаг 
.br
 image – ссылка на изображение шага 
.br
 
.PP
Definition at line \fB121\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bym\&.BYM_project\&.main_app\&.models\&.CookingStage\&.description = models\&.TextField()\fC [static]\fP"

.PP
Definition at line \fB135\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.CookingStage\&.dish\fC [static]\fP"

.PP
Definition at line \fB133\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.CookingStage\&.Dish\fC [static]\fP"

.PP
Definition at line \fB133\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.CookingStage\&.image = models\&.ImageField(null=True, blank=True, max_length=130)\fC [static]\fP"

.PP
Definition at line \fB137\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.CookingStage\&.on_delete\fC [static]\fP"

.PP
Definition at line \fB133\fP of file \fBmodels\&.py\fP\&.
.SS "bym\&.BYM_project\&.main_app\&.models\&.CookingStage\&.order = models\&.PositiveIntegerField()\fC [static]\fP"

.PP
Definition at line \fB136\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
