.TH "config.py" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbym\fP"
.br
.ti -1c
.RI "namespace \fBbym\&.BYM_project\fP"
.br
.ti -1c
.RI "namespace \fBbym\&.BYM_project\&.main_app\fP"
.br
.ti -1c
.RI "namespace \fBbym\&.BYM_project\&.main_app\&.config\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBbym\&.BYM_project\&.main_app\&.config\&.webdriver_name\fP = os\&.getenv('webdriver_name')"
.br
.ti -1c
.RI "list \fBbym\&.BYM_project\&.main_app\&.config\&.urls_lavka\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
