.TH "parser.py" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parser.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbym\&.BYM_project\&.main_app\&.parser\&.Parser\fP"
.br
.RI "Определяет базавый класс используемый для парсинга всех сайтов "
.ti -1c
.RI "class \fBbym\&.BYM_project\&.main_app\&.parser\&.Lavka\fP"
.br
.RI "Определяет класс используемый для парсинга лавки\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbym\fP"
.br
.ti -1c
.RI "namespace \fBbym\&.BYM_project\fP"
.br
.ti -1c
.RI "namespace \fBbym\&.BYM_project\&.main_app\fP"
.br
.ti -1c
.RI "namespace \fBbym\&.BYM_project\&.main_app\&.parser\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbym\&.BYM_project\&.main_app\&.parser\&.parse_by_address\fP (user_id, city_street, number)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
