.TH "search.py" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
search.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbym\&.BYM_project\&.main_app\&.search\&.SearchDish\fP"
.br
.RI "Класс реализует функционал поиска и сортировки блюд по строке поиска, фильтрам блюда, рекомендациям конткретному пользователю и указанному адресу "
.ti -1c
.RI "class \fBbym\&.BYM_project\&.main_app\&.search\&.SearchProduct\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbym\fP"
.br
.ti -1c
.RI "namespace \fBbym\&.BYM_project\fP"
.br
.ti -1c
.RI "namespace \fBbym\&.BYM_project\&.main_app\fP"
.br
.ti -1c
.RI "namespace \fBbym\&.BYM_project\&.main_app\&.search\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
