.TH "views.py" 3 "BYM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
views.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbym\&.BYM_project\&.main_app\&.views\&.UserApiView\fP"
.br
.ti -1c
.RI "class \fBbym\&.BYM_project\&.main_app\&.views\&.HomePageApi\fP"
.br
.ti -1c
.RI "class \fBbym\&.BYM_project\&.main_app\&.views\&.SearchDishApi\fP"
.br
.ti -1c
.RI "class \fBbym\&.BYM_project\&.main_app\&.views\&.ChangeCartApi\fP"
.br
.ti -1c
.RI "class \fBbym\&.BYM_project\&.main_app\&.views\&.ParseProductsApi\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbym\fP"
.br
.ti -1c
.RI "namespace \fBbym\&.BYM_project\fP"
.br
.ti -1c
.RI "namespace \fBbym\&.BYM_project\&.main_app\fP"
.br
.ti -1c
.RI "namespace \fBbym\&.BYM_project\&.main_app\&.views\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbym\&.BYM_project\&.main_app\&.views\&.HomePageView\fP (request)"
.br
.ti -1c
.RI "\fBbym\&.BYM_project\&.main_app\&.views\&.Dish\fP (request, id)"
.br
.ti -1c
.RI "\fBbym\&.BYM_project\&.main_app\&.views\&.FinalPage\fP (request)"
.br
.ti -1c
.RI "\fBbym\&.BYM_project\&.main_app\&.views\&.my_view\fP (request)"
.br
.ti -1c
.RI "\fBbym\&.BYM_project\&.main_app\&.views\&.update_counter\fP (request)"
.br
.ti -1c
.RI "\fBbym\&.BYM_project\&.main_app\&.views\&.parse_adress\fP (request)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BYM from the source code\&.
